name: CI

on: [push, pull_request]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-mac:
   runs-on: macos-12
   env:
     PYTHON_VERSION: 3.6.8
     MACOSX_DEPLOYMENT_TARGET: 12

   steps:
   - uses: actions/checkout@v2

   - name: Get Python
     run: curl -LO https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.9.pkg

   - name: Verify download
     run: shasum -a 256 -c <<< '4bcd53faffc98d193ef7cdccd5668de3829c702af4db45258819a84a2cab60d0 *python-3.6.8-macosx10.9.pkg'

   - name: Install Python
     run: sudo installer -pkg python-3.6.8-macosx10.9.pkg -target /

   - name: Setup venv and install dependencies
     run: |
       python3 -m venv venv
       source venv/bin/activate
       pip install --upgrade pip
       pip install -r requirements.txt
 
   - name: Build
     run: |
       source venv/bin/activate
       fbs freeze
       hdiutil create -volname Vial -srcfolder "target/Vial.app" -ov -format UDZO vial-mac.dmg
 
   - uses: actions/upload-artifact@v3
     with:
       name: vial-mac
       path: vial-mac.dmg

  build-win:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.6.x'

    - name: Setup venv
      run: |
        python -m venv venv
        . .\venv\Scripts\activate.ps1
        pip install -r requirements.txt
    - name: Install NSIS
      run: |
        Invoke-WebRequest "https://github.com/vial-kb/vial-deps/releases/download/v1/nsis-3.06.1-setup.exe" -UserAgent "wget" -OutFile nsis-3.06.1-setup.exe
        if ((Get-FileHash nsis-3.06.1-setup.exe -Algorithm sha256).Hash -ne "f60488a676308079bfdf6845dc7114cfd4bbff47b66be4db827b89bb8d7fdc52") { Write-Error 'SHA256 mismatch' }
        Start-Process -FilePath "nsis-3.06.1-setup.exe" -ArgumentList "/S", "/D=C:\Program Files (x86)\NSIS" -NoNewWindow -Wait
    - name: Build
      run: |
        . .\venv\Scripts\activate.ps1
        fbs freeze
        Compress-Archive -Path "target\Vial" -DestinationPath vial-win.zip
    - uses: actions/upload-artifact@v4
      with:
        name: vial-win
        path: vial-win.zip

    - name: Create installer
      run: |
        $env:Path += ";C:\Program Files (x86)\NSIS"
        . .\venv\Scripts\activate.ps1
        fbs installer
    - uses: actions/upload-artifact@v4
      with:
        name: vial-win-installer
        path: target\VialSetup.exe